### ISSUE TITLE
hakai_salmon_data: measurementUnit and measurementUnitID blank

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_data_guide#11]
There are no data in the measurementUnit or measurementUnitID columns in the measurementOrFact file. These are key pieces of information that need to be filled in. It would also be good to add measurementTypeID so that people can be clear what is meant by "length" or "weight".

**Comment by Br-Johnson** [comment]
I've updated all the `measurementUnit`(s) where appropriate (for length and weight), but where can I find the appropriate `meaurementUnitID` and `measurementTypeID` values?

**Comment by 7yl4r** [comment]
From https://dwc.tdwg.org/terms/#measurementUnit : 

> Recommended best practice is to use the International System of Units (SI).
> --
> *Examples*: mm, C, km, ha

For measurementTypeID it looks more complicated. 
The gbif OBIS schema [here](http://rs.gbif.org/extension/obis/extended_measurement_or_fact.xml) references a page on OBIS [here](http://rs.iobis.org/obis/terms/measurementTypeID) which is currently not loading for me.

**Comment by Br-Johnson** [comment]
For measurementUnitID I used terms from: http://vocab.nerc.ac.uk/collection/P06/current/

I haven't been able to find a controlled vocabulary term for fork_length, or mass however. So I'll keep this issue open for now.

**Comment by Br-Johnson** [comment]
Fork length has been added to NERC :)

http://vocab.nerc.ac.uk/collection/P01/current/FL01XX01/
