### ISSUE TITLE
rename the "Darwin Core Guide"?

### ISSUE THREAD

**Issue by 7yl4r** [ioos/bio_data_guide#111]
1. "Darwin Core Cookbook"
2. "Darwin Core Example Repository"

**Comment by MathewBiddle** [comment]
Are we looking to change only the title? Or are we looking to change the repo name? 

Title is an easy fix:
https://github.com/ioos/bio_data_guide/blob/bca7f60daa9a1ef45c2d7430638ef2a2d26bfc36/bio-data-guide/index.Rmd#L2

Changing repo will be more involved.

**Comment by 7yl4r** [comment]
If we wanted to change the name of the repo we might do `standardizing-marine-biodata-group`. Here I was thinking of changing the name of the "book" only. I like the "cookbook" title but I am curious what others think.

**Comment by MathewBiddle** [comment]
I don't think we should mess with the repo name at the moment.

I do like the title "Darwin Core Cookbook" but this doesn't read like a cookbook per se. More of a collection of Darwin Core Mobilization Examples.

**Comment by albenson-usgs** [comment]
Maybe we should have a poll in the SMBD on what to call it?

**Comment by MathewBiddle** [comment]
Did we ever decide on changing the name?

**Comment by MathewBiddle** [comment]
Rename to "Darwin Core Example Repository"

**Comment by albenson-usgs** [comment]
Admittedly I said I didn't want to debate this further but what about "Darwin Core Marine Example Compendium"? Repository is throwing me off for some reason and I think it's helpful to make clear that all these examples are marine specifically.

**Comment by MathewBiddle** [comment]
I'm good with "compendium". Fun word. I too had some concern with repository but didn't want to belabor the conversation.

Consider it decided.
