### ISSUE TITLE
build pdf_book fails

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_data_guide#117]
When we try to build the book using:
```R
bookdown::render_book("index.Rmd", "bookdown::pdf_book")
```
We get an Error (which causes a failure in the GH Action):
```
! LaTeX Error: File `https://mybinder.org/badge_logo.svg' not found.
```

See Action Error message: https://github.com/ioos/bio_data_guide/runs/6815885416?check_suite_focus=true#step:6:684

The error is occurring in the recently added datasets_edna example, when the README.md displays a badge for launching in Binder:
![](https://mybinder.org/badge_logo.svg) 
line in Readme: https://github.com/iobis/dataset-edna/blob/e7bb04218420b189e04d651f1653977f3a5d051d/README.md?plain=1#L4

To note, there are no issues when writing to html
```R
bookdown::render_book("index.Rmd");
```
or ePub:
```R
bookdown::render_book("index.Rmd", "bookdown::epub_book")
```

So, something is busted when trying to convert the following latex line to pdf.
```latex
\href{https://mybinder.org/v2/gh/iobis/dataset-edna/HEAD?labpath=src\%2Fconversion_code.ipynb}{\includegraphics{https://mybinder.org/badge_logo.svg}}
```

**Comment by 7yl4r** [comment]
It looks like [this issue](https://tex.stackexchange.com/q/5433/272069). I am guessing `bookdown` only uses LaTeX for generating the `.pdf` and that is why that one is not working. The best fix would be to submit a PR to bookdown to enable usl-usage as described in the answers in that aforementioned S.E. answer. Quick hack would be to replace the https link with a local file or drop it altogether - we don't really *need* the pretty button, do we? 😬

**Comment by MathewBiddle** [comment]
Trouble is, I'm trying to submodule that readme from https://github.com/iobis/dataset-edna. So we ether make the change in that repo, or do some fancy stuff in the GH Action to clean up that line (thinking a simple `sed` command will work).

**Comment by MathewBiddle** [comment]
See PR #118 for details on how I hacked this. Not elegant, but it works for now.
