### ISSUE TITLE
new dataset: MBON ZooPlankton eDNA

### ISSUE THREAD

**Issue by 7yl4r** [ioos/bio_data_guide#120]
@annidjurhuus is working to align 2016 MBON cruise data. 
A [draft occurrences.csv](https://github.com/ioos/bio_data_guide/blob/main/datasets/mbon_eDNA_zooplankton_anni/MBON%20ZOO_Tylar.xlsx%20-%20Sheet1.csv) file has been produced.

I *think* this is just the manually-ID'd zooplankton from Jaime (similar to the other data in [USF-IMaRS/zoo-taxonomy-to-darwin-core](https://github.com/USF-IMARS/zoo-taxonomy-to-darwin-core)), but the intention is to also include the eDNA data from this cruise. 

I have started some documentation [here](https://github.com/ioos/bio_data_guide/tree/main/datasets/mbon_eDNA_zooplankton_anni).

**Comment by MathewBiddle** [comment]
related? #135

**Comment by 7yl4r** [comment]
Good find! I am going to mark this as duplicate of the other one. 

A note for future Tylars: please remember to search to see if a related issue already exists before opening a new one. :facepalm:

**Comment by 7yl4r** [comment]
> Are these the same? I thought one was eDNA and the other was plankton tows?

You are right. I have fixed the titles of the two issues to differentiate them.

**Comment by albenson-usgs** [comment]
We have discovered that this is actually a duplicate of #135

**Comment by 7yl4r** [comment]
:dizzy_face:
