### ISSUE TITLE
What workflow should users use to contribute to this repository?

### ISSUE THREAD

**Issue by zmonteith** [ioos/bio_data_guide#13]
@7yl4r @albenson-usgs How should users contribute to this repository? It appears I don't have permission to push or create branches. Should I fork and create a pull requests?

Thanks!

**Comment by 7yl4r** [comment]
This is a good point of discussion for our upcoming meeting. 
Formally, forks and pull requests are best practice for using git, but I often give out permissions like candy to encourage participation and lower the bar of entry for new users.

**Comment by zmonteith** [comment]
Sounds good. I agree it would be a great topic for the meeting.
I'm happy to go with the 'fork and pull' format, but just wanted to check in before going to far down that road.

**Comment by Br-Johnson** [comment]
I think it makes sense for those of us that were at the workshop in Ann Arbor to be able to commit to master, or a little safer would be to grant 'commit to develop branch' privileges and require a pull request to go to master. That way we can work on our own data conversions without submitting a pull request. Best practice should be to submit a PR when editing someone else's material, or editing any of the guide/documentation though.

**Comment by mwengren** [comment]
@zmonteith check your GitHub account, you should already have an invite to join a team under the IOOS org with the correct permissions.  When we moved this over, I copied everyone before as a member on this team (invitation must be accepted to take effect though).  

At the moment @albenson-usgs has maintainer rights to the team to add new people, although I believe they have to be members of the IOOS org first, which I believe requires an org admin like myself.  

We can't give admin rights to repos out, but we can work to figure out the best way to manage permissions to make things work smoothly for everyone.

**Comment by zmonteith** [comment]
Thanks @mwengren! I must have missed the email earlier, but I've found it now so that should answers my question.

I'll leave this issue open until after tomorrow's SMBD meeting in case there are useful points to add.

**Comment by 7yl4r** [comment]
Meeting consensus was let's keep it simple. 
Invite collaborators liberally and feel free to edit on the master.
Branches & merges or forks & PRs are welcome, but not required until the group grows to a size where we start hitting merge conflicts.
