### ISSUE TITLE
[dataset]: CETUS dataset

### ISSUE THREAD

**Issue by MafsCorreia** [ioos/bio_data_guide#152]
### Contact details

anamafaldacorreia@gmail.com

### Dataset Title

CETUS: Cetacean monitoring surveys in the Eastern North Atlantic

### Describe your dataset and any specific challenges or blockers you have or anticipate.

The dataset is described in two data papers:

https://www.nature.com/articles/s41597-022-01803-7

https://www.nature.com/articles/s41597-019-0187-2

We published the datset with the DwC format at EurOBIS, with the support of a colleague. I wish to learn more about the process in order to keep updating the dataset and be able to upload other datasets that may come up. I will work with the raw data of CETUS, now from 2012 to 2019.

**Comment by 7yl4r** [comment]
cetacean occurrence data from Platforms of Opportunity (2012-2019). Published in OBIS through VLIZ from 2012 to 2017, here: https://ipt.vliz.be/eurobis/resource?r=cetus_cetaceans#anchor-versions

**Comment by albenson-usgs** [comment]
Ana, thank you for your interest in the workshop. From what I can tell I don't think you attended and since you should have assistance from EurOBIS for publishing future versions of this dataset, I'm going to close this ticket.
