### ISSUE TITLE
[dataset]: Long-term MPA Monitoring / Coastal Biodiversity Surveys

### ISSUE THREAD

**Issue by MarineLebrec** [ioos/bio_data_guide#165]
### Contact details

mlebrec@mbari.org

### Dataset Title

MARINe/PISCO: Intertidal MARINe Coastal Biodiversity Surveys

### Describe your dataset and any specific challenges or blockers you have or anticipate.

Some preliminary code has been written to convert the raw data to DwC standards by my predecessor and I aim to pick that work up. I have little experience converting data to DwC so am keen to get some hands on practice. 

### Link to "raw" Data Files.

https://data.piscoweb.org/metacatui/view/doi%3A10.6085%2FAA%2Fmarine_cbs.5.5

**Comment by albenson-usgs** [comment]
This would be an update of these two datasets, I think:
https://www1.usgs.gov/obis-usa/ipt/resource?r=marine_ltm_photoplot_surveys
https://www1.usgs.gov/obis-usa/ipt/resource?r=marine_ltm_seastar_katharina_count

Excited to have you join us Marine!

**Comment by MarineLebrec** [comment]
Very excited to be involved with this! 

The datasets I am hoping to use are separate MARINe datasets which have not yet been converted to Darwin Core or submitted to OBIS. The ones that have been submitted to OBIS are their long-term monitoring datasets, but these new ones are their "coastal biodiversity surveys".

**Comment by albenson-usgs** [comment]
Got it! Thanks!

**Comment by MathewBiddle** [comment]
These data have been mobilized:
* OBIS: https://obis.org/dataset/fbf4cb59-cef3-43be-b0ab-0dbab5f51740
* IPT: https://ipt-obis.gbif.us/resource?r=marine_ltm_photoplot_surveys
* GBIF: https://www.gbif.org/dataset/e24dcb47-89f9-4481-a8ac-c38ef26b2865
* DOI: https://doi.org/10.15468/ranfdh

Citation:
```
United States Geological Survey: MARINe/PISCO: Intertidal: MARINe Long-Term Monitoring Surveys: Photo Plots and Transects Summarized https://doi.org/10.15468/ranfdh accessed via GBIF.org on 2023-05-04.
```

**Comment by albenson-usgs** [comment]
Hey Matt- those aren't the correct links for this dataset. These are the correct ones:

- IPT: https://ipt-obis.gbif.us/resource?r=marine_cbs_point_contact_surveys
- GBIF: https://www.gbif.org/dataset/58ffefab-20aa-4cec-b0c0-dd7330ed7280
- OBIS: https://obis.org/dataset/bb638343-bbc9-464d-88d8-18d9ba29ecdd
- DOI: https://doi.org/10.15468/5rpuzd

Citation: 
Raimondi P (2023). MARINe/PISCO: Intertidal: MARINe Coastal Biodiversity Surveys: Point Contact Surveys Summarized. Version 1.1. United States Geological Survey. Sampling event dataset https://doi.org/10.15468/5rpuzd accessed via GBIF.org on 2023-05-04.

This dataset is complete. Closing with this comment.

**Comment by MathewBiddle** [comment]
@albenson-usgs Thanks for catching that. Don't know how I messed that one up :cry: 

I 'hid' my comment to not confuse folks. Sorry for the mistake.
