### ISSUE TITLE
Annotated bibliography for publications using data from OBIS/GBIF

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_data_guide#17]
During our December call, we discussed the fact that what's most beneficial for sharing the data (and creating the metadata) was thinking about what analyses would be using these data and what they would need to know. In order to get a better understanding of this, Brett suggested we create an annotated bibliography showcasing how the data are being used.

**Comment by 7yl4r** [comment]
I'd Ike to take this on but am not sure what form this bibliography should take. Spreadsheet? Markdown document? Something else that helps track publications?

**Comment by Br-Johnson** [comment]
I'm partial to [.bibTex](http://www.bibtex.org/Using/). Both Zotero and Mendeley reference managers support those formats. Sometimes journals require a .bib file as well. Anything plain text is best though. Maybe just start it off as a .txt?

**Comment by 7yl4r** [comment]
I created a basic bibtex file in `./docs/` to get us started. 
I think this may grow into something bigger in the future but for now please add any interesting citations using GBIF/OBIS there.

**Comment by albenson-usgs** [comment]
Citations can be found here https://obis.org/library/ and here https://www.gbif.org/resource/search?contentType=literature&literatureType=journal&relevance=GBIF_USED&peerReview=true
