### ISSUE TITLE
create mailing list for SMBD WG

### ISSUE THREAD

**Issue by 7yl4r** [ioos/bio_data_guide#176]
copied from https://github.com/ioos/bio_mobilization_workshop/issues/24

Create a google group mailing list for the SMBD WG?

https://groups.google.com/

**Comment by MathewBiddle** [comment]
I cannot create a Google Group. NOAA uses the Google Suite and has blocked the ability to create a group. I think I can be an `Owner` or `Manager` of the list, I just can't create it :cry:

**Comment by 7yl4r** [comment]
I created [the SMBD@googlegroups.com group](https://groups.google.com/g/smbd) and sent you an invite. We can now add emails for members, managers, etc.

**Comment by MathewBiddle** [comment]
In the end we decided not to create a mailing list for this group. We can reopen this issue if we'd like to revisit later.
