### ISSUE TITLE
Create a how-to document for navigating the NERC Vocabulary

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_data_guide#18]
During our December call we discussed the difficulties and vagaries in navigating the NERC Vocabulary. It's still unclear to me at least what the best way to find the term you are looking for is. It's not as simple as doing a search for that term. Or at least I haven't found it to work that way. It would be great to create a how-to document on navigating the NERC Vocabulary so others don't need to flail around as we have searching for what we're looking for (and making the final determination that it can't be found if the term is not in there).

**Comment by emiliom** [comment]
I haven't used "the NERC Vocabulary" much at all, and not at all for OBIS/bio purposes. With that caveat in mind:
- Are you referring to one specific NERC-hosted vocabulary, or any of them? My understanding is that the [NERC Vocabulary Server (NVS)](https://www.bodc.ac.uk/resources/products/web_services/vocab/) hosts many vocabularies (collections). For example, [CF standard names](http://vocab.nerc.ac.uk/collection/P07/current/), which is also found in other systems. Are there, say, a couple of them that you've found most relevant?
- Speaking of CF standard names, it sounds like a browser along the lines of the [CF Standard Names Vocabulary Browser](https://mmisw.org/cfsn/#/) would be very helpful!
- Maybe a conversation with ESIP folks would be helpful in either uncovering relevant resources or thinking about future possibilities? I'm thinking of the [Semantic Technologies Committee](http://wiki.esipfed.org/index.php/Semantic_Technologies) or the [Community Ontology Repository (COR) Cluster](https://www.esipfed.org/get-involved/collaborate)

My 2 cents

**Comment by albenson-usgs** [comment]
1. Yes there are certain ones that are more relevant to what we're doing. I _think_ P06 but maybe @Br-Johnson would know. I know he's been digging into this lately looking for the right vocabulary for the measurementUnitID term in Darwin Core.
2. YES! Something like that would be fantastic. I think that's exactly what I'm hoping for.
3. Good call. I'll send them an email. Although maybe I should ask the OBIS folks or the BODC folks first.

**Comment by emiliom** [comment]
To make `P06` (*"BODC-approved data storage units. Terms approved for use by BODC to describe the measurement units for data held in its repositories."*) more tangible, here's its NERC/NVS link: http://vocab.nerc.ac.uk/collection/P06/current/. Is that the best, or only, vocabulary page/resource available from NERC for P06? I don't know if NERC has other viewers/browsers.

Also, for what it's worth, in CF / netcdf land, udunits is more common:
- https://www.unidata.ucar.edu/software/udunits/
- https://mmisw.org/ont/mmi/udunits2-common
- https://mmisw.org/ont/mmi/udunits2-base

**Comment by bbest** [comment]
Looks like this NERC vocabulary search tool works decently for finding terms across collections:

https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/

For example, searching for "nanograms" to get at 'nanograms per microliter', leads to 8 results from [P06](https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/P06/), including [UNUL: Nanograms per microlitre](http://vocab.nerc.ac.uk/collection/P06/current/UNUL/):

![image](https://user-images.githubusercontent.com/2837257/72016603-f341c880-3218-11ea-9310-a9f33dea1453.png)

**Comment by mobb** [comment]
General question: what guidelines do you folks use for 
- choosing vocabulary with the best match (to your data's concept)
- choosing identifier for the term that is most reliable
- determining which presentation of a vocabulary is canonical

thanks! at LTER/MBON we have look quite a bit at NERC, and it can be a bit overwhelming.

**Comment by albenson-usgs** [comment]
OBIS recommends NERC, I think mostly because EurOBIS has a strong connection with BODC, so that's really the one I've been focused on but there are obviously others. Vicky mentioned BCO-DMO on the call today which I wasn't even aware they had a controlled vocabulary. We're working on a document (https://github.com/ioos/bio_data_guide/blob/master/docs/controlled-vocabs.md) if you want to look or contribute.

**Comment by MathewBiddle** [comment]
Just wanted to add a little something to the conversation.  There is a [NERC Vocabulary Server (NVS) github organization](https://github.com/nvs-vocabs) which has repositories for the various vocabularies where you can ask questions or hopefully get guidance.  I typically use the [NERC Vocabulary Search](https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/), "Simple Search Within a Vocabulary" and select the vocabulary of interest (typically [P01](https://www.bodc.ac.uk/resources/vocabularies/vocabulary_search/P01/) for variables). 

I think it would be helpful to have a table for the [various vocabularies the NVS has](https://vocab.nerc.ac.uk/collection/), so you can more easily narrow down which one you want to search. [Here is a csv file](https://github.com/ioos/bio_data_guide/files/5531553/NVS_collections.txt) (I have to add it as a .txt for github tickets) which contains the Collection identifier, the title of the vocabulary, and who manages it. I find this easier to navigate. Maybe we can add that table to the documentation [here](https://ioos.github.io/bio_data_guide/intro.html#controlled-vocabularies)?

To note: I found something where one of the [NVS repositories](https://github.com/nvs-vocabs) has an example of using [python to build a SPARQL query for NVS](https://github.com/nvs-vocabs/nvsSPARQL/blob/main/QueryNVSInPython.ipynb). I wonder if it would be useful to explore building a package similar to [pyworms](https://github.com/iobis/pyworms) or [taxize](https://github.com/ropensci/taxize), but for the NVS? Would people use a tool like that? Or, is there still too much human intervention necessary to find the appropriate term?

**Comment by albenson-usgs** [comment]
The working group decided this was a bit out of scope for the group and the NVS has advanced since this ticket was originally created. Closing.
