### ISSUE TITLE
recommended controlled vocabulary for lifeStage

### ISSUE THREAD

**Issue by 7yl4r** [ioos/bio_data_guide#182]
Looking at [the dwc docs for occurrence lifeStage](https://dwc.tdwg.org/terms/#dwc:lifeStage), @cperaltab and I are wondering:

1. what controlled vocabularies are (suggested|popular)
2. how to specify which controlled vocabulary is being used for this column

**Comment by albenson-usgs** [comment]
GBIF has this: https://registry.gbif.org/vocabulary/LifeStage/concepts
NERC has this: http://vocab.nerc.ac.uk/collection/S11/current/ but I'm not the best one to point to where in NERC to find appropriate IRIs so take that link with a grain of salt.
There might be other ontologies out there that have life stage terms.
