### ISSUE TITLE
Add SanctSound Passive Acoustic Monitoring crosswalk example to the compendium

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_data_guide#188]
Recently the [SanctSound passive acoustic monitoring species observations](https://github.com/ioos/bio_data_guide/issues/147) were shared to OBIS and GBIF. This is the first PAM dataset worked on within the SMBD and published via OBIS-USA. It would serve as a good example not only of PAM data but also working with data shared via and ERDDAP. It would be great to get it added to the [Darwin Core Marine Example Compendium](https://ioos.github.io/bio_data_guide/applications.html) for others to reference.

**Comment by MathewBiddle** [comment]
need to point to the notebook at https://github.com/ioos/bio_data_guide/blob/f528c23171b893ed6dcf4bc9495f37d793ee88c9/bio-data-guide/02-application.Rmd#L8

**Comment by MathewBiddle** [comment]
There were a few notebooks that went into this effort. I put together a readme that should document all the various jupyter notebooks https://github.com/ioos/bio_data_guide/blob/main/datasets/SanctSound/README.md

**Comment by MathewBiddle** [comment]
@albenson-usgs FYI https://ioos.github.io/bio_data_guide/applications.html#passive-acoustic-monitoring

**Comment by albenson-usgs** [comment]
Looks great! Thank you!
