### ISSUE TITLE
submodule fetch broken in GHA

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_data_guide#191]
See https://github.com/ioos/bio_data_guide/actions/runs/7185372819/job/19568532656

Error:
```
Error: fatal: Fetched in submodule path 'datasets/dataset-edna'
```

**Comment by 7yl4r** [comment]
The linked error

```
  Error: fatal: Fetched in submodule path 'datasets/dataset-edna', but it did not contain 9d2b82a1a94d4b3f74325b0f284ad4c50618e6c1. Direct fetching of that commit failed.
```

looks like an issue fetching a particular commit but the [.gitmodules file](https://github.com/ioos/bio_data_guide/blob/main/.gitmodules) does not specify a commit.
I wonder if this is a cache that got messed somewhere.

**Comment by MathewBiddle** [comment]
Interesting - submodule pinned to a specific commit that doesn't exist 

https://github.com/iobis/dataset-edna/tree/9d2b82a1a94d4b3f74325b0f284ad4c50618e6c1

I'll try to hash this out locally.
