### ISSUE TITLE
[dataset]: Animal_Tracking_Dataset

### ISSUE THREAD

**Issue by nandapm** [ioos/bio_data_guide#208]
### Contact details

nandapm2010@gmail.com

### Dataset Title

Animal Tracking Dataset

### Describe your dataset and any specific challenges or blockers you have or anticipate.

Genomics data has different data types, which are in different data formats. The main problems I see is dealing with many fields of different formats and different information

### Info about "raw" Data Files.

The raw data is in an excel file with a header.

**Comment by nandapm** [comment]
[Banco de Dados de Rastreamento LAATM.xlsx](https://github.com/ioos/bio_data_guide/files/14065440/Banco.de.Dados.de.Rastreamento.LAATM.xlsx)

**Comment by MathewBiddle** [comment]
@nandapm did you mean to close this issue? Or do you plan on working on it during the workshop?
