### ISSUE TITLE
[dataset]: 

### ISSUE THREAD

**Issue by mohab1302** [ioos/bio_data_guide#231]
### Contact details

mohab.mahmoud1302@gmail.com

### Dataset Title

Marine Biological Observation Dataset

### Describe your dataset and any specific challenges or blockers you have or anticipate.

I'm seeking assistance in obtaining a marine biological observation dataset for an upcoming workshop. As I don't have my own dataset to work on, I'm reaching out for help in finding a suitable dataset to use for the workshop. 
Any assistance in providing or directing me to an appropriate dataset would be greatly appreciated. Thank you!

**Comment by 7yl4r** [comment]
check out https://github.com/iobis/dataqueue/issues
