### ISSUE TITLE
MARINe/PISCO: intertidal swath density surveys

### ISSUE THREAD

**Issue by MarineLebrec** [ioos/bio_data_guide#244]
### Contact details

mlebrec@mbari.org

### Dataset Title

MARINe/PISCO: Intertidal: MARINe Coastal Biodiversity Surveys: Swath Surveys Summarized

### Describe your dataset and any specific challenges or blockers you have or anticipate.

This dataset includes ~20 years of intertidal swath transects to estimate the density of seastars and abalone from a number of monitoring sites along the US West Coast, managed by the Multi-Agency Rocky Intertidal Network (MARINe). I worked on mobilizing a similar dataset last year (intertidal point contact data). This workshop will allow me to devote time to mobilizing another large dataset to OBIS/GBIF and answer any questions I have along the way. 

### Info about "raw" Data Files.

The data is published to DataONE here: https://data.piscoweb.org/metacatui/view/doi%3A10.6085%2FAA%2Fmarine_cbs.11.6

**Comment by MarineLebrec** [comment]
I made some great progress on this dataset in our recent Data Mobilization Workshop - thanks to the organizers! The DwC-A that I generated is ready for review. Once everything looks good, @sformel-usgs will train me up on using the OBIS IPT so I can submit this myself. 

- [Link to conversion workflow in an IPython notebook](https://github.com/CeNCOOS/MPA_data_integration/blob/main/MARINe/CBS_swathsurveys/MARINe_CBS_swathsurveys_conversion.ipynb)
- [Link to DwC tables (event core + extensions)](https://github.com/CeNCOOS/MPA_data_integration/tree/main/MARINe/CBS_swathsurveys/processed_files). 

Thanks for any feedback! 😄

**Comment by sformel-usgs** [comment]
@MarineLebrec I will try to look at this in the next week, but anyone else is welcome to give it a review too.

**Comment by sformel-usgs** [comment]
@MarineLebrec Just a quick note to say I'm working on this.  I had hoped to have it done today but the NERC vocab has become a bit of a rabbit hole.  I'll keep you posted.

**Comment by MarineLebrec** [comment]
Update: I've been able to make the suggested corrections to my DwC-A, which is reflected in the same Github repo: https://github.com/CeNCOOS/MPA_data_integration/tree/main/MARINe/CBS_swathsurveys 

We'll be meeting on June 17th to go through the IPT, EML metadata, and any other last steps! Thanks for all your help.

**Comment by MarineLebrec** [comment]
Thanks to much appreciated help from @sformel-usgs we got this dataset published so I'll close this issue :) 
GBIF: https://www.gbif.org/dataset/fdcdc447-2032-4edf-9519-0ec89ae1b9c5 
OBIS: https://obis.org/dataset/30884b6c-e8e1-453c-af20-7ed8318489c6
