### ISSUE TITLE
hakai_seagrass: # events = # occurrences?

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_data_guide#25]
@zmonteith I may have done something wrong, I didn't see the output files in the hakai_seagrass folder so I ran the R script to create the seagrassEvent and seagrassOccurrence data tables, but there are the same number of observations in the event file and the occurrence file. Is this accurate? You only have one species at each collection event?

**Comment by zmonteith** [comment]
this is correct. This dataset is point observations of seagrass habitat and density variables, each observation (event) is *Zostera marina* presence (occurrence). These surveys are focused more on presence and habitat, with separate surveys focused on fish and invertebrate diversity.
