### ISSUE TITLE
[dataset]: intertidal COI metabarcoding data

### ISSUE THREAD

**Issue by meghanmshea** [ioos/bio_data_guide#258]
### Contact details

mshea@stanford.edu

### Dataset Title

Environmental DNA metabarcoding differentiates between micro-habitats within the rocky intertidal

### Describe your dataset and any specific challenges or blockers you have or anticipate.

My dataset is an eDNA metabarcoding dataset from sampling done over the tidal cycle at three discrete locations in one rocky intertidal ecosystem. 

I attended the 2023 Marine Biological Data Mobilization Workshop and started working on this dataset, and then it ended up on a back burner. Now, the first paper based on this dataset is nearing publication, and I'm realizing it would be so nice to have the dataset also published to OBIS/GBIF before the paper is finalized so that I can include the links in the paper. So, perhaps too lofty a goal, but I'm trying to get everything in order quickly!

I think I am close to having the dataset aligned to Darwin Core, through a combination of some data wrangling myself (code in the RMarkdown file in the attached repo) and also using the the beta version of a GBIF [web-based data formatting tool](https://edna-tool.gbif-uat.org/) for DNA-derived data. But, I'm realizing that I don't actually know what happens once I have my Darwin Core archive finalized. 

Could someone point me in the right direction for what I'll do next?

### Info about "raw" Data Files.

https://github.com/meghanmshea/intertidal-eDNA

**Comment by MathewBiddle** [comment]
@meghanmshea you came to the right place! Once you have the Darwin Core files at a state where you'd like someone to review them, reach out to your appropriate OBIS node manager (see [contacts](https://obis.org/contact/)). I think that would be @sformel-usgs for OBIS-USA in this case. 

Add your DarwinCore files to your repository and notify the node manager where to access them and they are ready for review. That would probably be easiest to do using this issue.

**Comment by meghanmshea** [comment]
My Darwin Core files aren't fully finalized yet (bullets below on what I think is still missing), but would love to know if I'm on track with everything else, @sformel-usgs 
-  I'm working with the folks behind the GBIF [web-based data formatting tool](https://edna-tool.gbif-uat.org/) for DNA-derived data to sort out a glitch where my Extended Measurement or Fact salinity/temperature values aren't being properly saved into the Darwin Core archive
- I'd love to add additional metadata like the Purpose/Temporal scope/Geographic scope/Taxonomic scope/Methodology sections in Katherine Silliman's [great dataset](https://www.gbif.org/dataset/9012def0-bd87-48a0-ac9e-e0e78dd37689#description), but am not sure how/when to do that.

Darwin Core archive as a .zip is [here](https://github.com/ioos/bio_data_guide/files/14529239/archive.2.zip), and the submission can also be viewed in the gbif-uat test environment [here](https://www.gbif-uat.org/dataset/35f29656-ec1a-485e-827b-63a800efbed7#description).

**Comment by meghanmshea** [comment]
Update: I actually think I've managed to fix most of the bullets from above (although there are still some metadata fields that I'm not sure how to add)! So, hoping I'm fairly close and would love to know if there's anything I'm missing and what the next steps are, @sformel-usgs 

Updated Darwin Core archive as a .zip is [here](https://github.com/ioos/bio_data_guide/files/14542290/archive.zip), and can also be viewed in the gbif-uat test environment [here][(https://www.gbif-uat.org/dataset/27db0c0f-0f6e-4919-bb80-2a582fb45886](https://www.gbif-uat.org/dataset/dc453fb7-2752-4adc-bd34-c3a042de1701).

**Comment by sformel-usgs** [comment]
We ended up publishing it here: https://ipt-obis.gbif.us/manage/resource.do?r=shea_boehm_2024 this evening  Congrats to @meghanmshea and her hard work!

**Comment by MathewBiddle** [comment]
That link didn't work for me. But this one does: https://ipt-obis.gbif.us/resource?r=shea_boehm_2024

**Comment by sformel-usgs** [comment]
Oops, in my excitement I included my manager view in the link.  Thanks for providing the correct one!

**Comment by MathewBiddle** [comment]
To close this out, here are the various endpoints for these data:

* GBIF - https://www.gbif.org/dataset/9358fbd7-cfd0-4eab-99fa-0934396a0529
  * GBIF DOI - https://doi.org/10.15468/33artc
* OBIS - https://obis.org/dataset/54bc0e9c-e857-4216-a6ce-46cd6ae58cd7
* OBIS-USA IPT - https://ipt-obis.gbif.us/resource?r=shea_boehm_2024

Congrats all! 🍾

**Comment by meghanmshea** [comment]
Just in case it's useful to others going through this process, I wanted to keep a record of some of the changes/revisions/edits I'm working on now that dataset has been published:

1. I ended up with some strange-seeming scientific name ID flags on some of the occurrences in the dataset, which, with @sformel-usgs's help, has been submitted to the GBIF HelpDesk and opened as a GitHub issue [#5241](https://github.com/gbif/portal-feedback/issues/5241). 
2. I'm working through the [OBIS manual](https://manual.obis.org/vocabulary.html#map-emof-measurement-identifiers-to-preferred-bodc-vocabulary) to figure out the right controlled terms/identifiers for the salinity + temperature EMOF I included
3. I also have some small revisions I'm compiling for a future update: including minimumDepthInMeters (0) and maximumDepthInMeters (.5) for OBIS, and maybe some small tweaks to the metadata.

**Comment by meghanmshea** [comment]
@sformel-usgs, I've finally gotten around to compiling a full list of small revisions for this dataset:

1. There are two places in the metadata currently that include a link to the pre-print associated with this dataset: the Description and the Bibliography. These hyperlinks could both be updated to the DOI for the published paper: http://dx.doi.org/10.1002/edn3.521 _[but this is not a huge deal to change, since the pre-print link does also have a link to the published paper]_. 
2. For OBIS, minimumDepthInMeters (0) and maximumDepthInMeters (.5) should be added.
3. For the EMOF, I've tried to figure out the right URIs for measurementUnitID and measurementTypeID, which I think should be the following (but open to suggestions/corrections if these don't seem right!):

For the salinity measurement type:
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/UPPT/
- measurementTypeID: http://vocab.nerc.ac.uk/collection/P01/current/SSALPR01/

For the temperature measurement type: 
- measurementUnitID: http://vocab.nerc.ac.uk/collection/P06/current/UPAA/
- measurementTypeID: http://vocab.nerc.ac.uk/collection/P01/current/TEMPDTNX/

**Comment by sformel-usgs** [comment]
These updates were made today. Thanks for your patience!
