### ISSUE TITLE
hakai_seagrass: occurrenceID

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_data_guide#26]
@zmonteith there are 3097 observations in the occurrence file but only 3013 unique occurrenceIDs. There needs to be a unique occurrenceID for each observation.

**Comment by zmonteith** [comment]
Similar to #31, and #23, this issue was due to duplicates in the raw data. It has been addressed by 27dcb16d06135100f98e34df406d785e03cf3df6
