### ISSUE TITLE
Update DNA-derived Data page with guidance about record-level terms

### ISSUE THREAD

**Issue by laurabrenskelle** [ioos/bio_data_guide#265]
The [DNA-derived Data Extension page](https://ioos.github.io/bio_mobilization_workshop/edna-extension/) details how to use this extension, but it might be helpful to include guidance on terms in the regular DwC that have best practices when reporting DNA-derived occurrence data.

Example: `dwc:basisOfRecord`: `MaterialSample`

**Comment by MathewBiddle** [comment]
this should be in the workshop repo. I created a new issue over there https://github.com/ioos/bio_mobilization_workshop/issues/132
