### ISSUE TITLE
Fix GH Action Install packages

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_data_guide#266]
https://github.com/ioos/bio_data_guide/actions/runs/8804894787/job/24166283620#step:5:1

**Comment by MathewBiddle** [comment]
this shouldn't take 30 mins!

**Comment by 7yl4r** [comment]
There are github actions that help manage dependencies & do caching [ref](https://github.com/r-lib/actions?tab=readme-ov-file#list-of-actions). I think the first step towards doing this is to move the dependency list into a DESCRIPTION file.

**Comment by MathewBiddle** [comment]
I'm also wondering if it should be ported over to [quarto](https://quarto.org/) as that might be easier to manage and limit dependencies.

**Comment by MathewBiddle** [comment]
Thanks, @bbest! I finally got the action to work after adding a bunch of new packages to the GH Action - install step. It still takes 23 minutes to install, build, and publish the rbookdown.

Action Run: https://github.com/ioos/bio_data_guide/actions/runs/10704923264
Changes I made: https://github.com/ioos/bio_data_guide/compare/99f04e2fb74f2f3b0b21dbadd2ca37fea75bf0d1..main#diff-d9e9c628038e6474c0572aad848b58690c7222f3092b90aa09d0c3cb11e194ccL32

The current settings should allow you to submit PRs and the Actions will run. Can you advise on the additional privileges you need?

**Comment by bbest** [comment]
Hi @MathewBiddle,

I should've forked from `ioos/bio_data_guide`, but did make considerable progress with a fully functional Quarto book (generating html/pdf/epub) that renders in 3.5 minutes with this pull request:

https://github.com/MathewBiddle/bio_data_guide/pull/7

**Comment by MathewBiddle** [comment]
We are live now! Thanks @bbest for this significant contribution!

https://ioos.github.io/bio_data_guide/
