### ISSUE TITLE
hakai_seagrass: transect_dist

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_data_guide#27]
@zmonteith Would it make sense to put transect_dist into [samplingEffort](https://dwc.tdwg.org/terms/#dwc:samplingEffort)?

**Comment by zmonteith** [comment]
Good point. Since the number of occurrences is directly related to the transect length (ie. measurements at every 5m point intercept) in this dataset, transect length would be equivalent to samplingEffort.

I'll include the full transect length (ie. 30m) as samplingEffort in the Event table
