### ISSUE TITLE
hakai_seagrass: WoRMS output info

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_data_guide#29]
@zmonteith I think we should drop most of the columns from the WoRMS output. All we really need from there is the LSID which is the [scientificNameID](https://dwc.tdwg.org/terms/#dwc:scientificNameID). We can keep the taxonomic hierarchy (Kingdom, Phylum, Class, etc) but everything else should be dropped out (isMarine, ScientificName_accepted, Authority_accepted, etc). Again this might just be an artifact of me running the code since the output csvs aren't in the folder.

**Comment by zmonteith** [comment]
Sounds good. This was I removed most of the NA fields in a previous commit, so fixed now.
