### ISSUE TITLE
hakai_seagrass: merging the event table with the occurrence table

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_data_guide#31]
@zmonteith when I try merging the event table with the occurrence table using eventID as the merging column, I end up with 3269 observations in the table which is just slightly more than either of the individual tables. Any idea what's going on there?

**Comment by zmonteith** [comment]
Looks like this was due to some duplicate observations in the raw data, I've removed these duplicates prior to creating the event and occurrence tables which appears to have corrected the issue.
