### ISSUE TITLE
Land of the lost (vocabulary terms)

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_data_guide#32]
Sometimes despite our best efforts, vocabulary terms that match our data are nowhere to be found. List them here so we can work with BODC or another vocabulary entity to get them added. Or maybe someone will know where to find the term you need and can match you up! Either way list your lost terms here.

**Comment by mobb** [comment]
So you know, SBC MBON (and the LTERs) are annotating the measurements in its primary EML with terms from this ontology: http://bioportal.bioontology.org/ontologies/ECSO
It's OWL, so the goal is to have it added to OBO. 
We also use a lot of terms from ENVO, both directly, and as imported to ECSO.

**Comment by Br-Johnson** [comment]
Hi @mobb. Thank you for sharing the Bioportal ecosystem ontology. Looks very useful. 

I didn't know what some of these acronyms meant so after a bit educated googling I found this:

I'm assuming OWL refers to [this](https://www.w3.org/2007/OWL/wiki/Direct_Semantics)? 
And OBO refers to the [Open Biomedical Ontologies](https://www.nature.com/articles/nbt1346)?

ESCO I think refers to the Ecosystems Ontology you linked to and I'm assuming ENVO refers to [this](http://bioportal.bioontology.org/ontologies/ENVO) controlled vocab from BioPortal. 

Thanks!

**Comment by mobb** [comment]
Hi @Br-Johnson - nominal answer to both questions is 'yes'. However there are a few nuances. 

Bioportal does not own any of these ontologies, it is a repository that offers some services for querying and presenting ontologies. Much the same way that OBIS/GBIF aggregate organism data and what BODC offers for SKOS vocabularies with the NERC vocab server. Bioportal has an icon in the upper right for the ontology's home website

ECSO is managed by the NCEAS (National Center for Ecological Analysis and Synthesis) -- Full disclosure: I work on it. And the LTER network (among others) collaborates with ENVO.

If you are interested, here is a poster from 2018 AGU that explains how we use ECSO and ENVO, with some background info on how ontology fits into the vocabulary landscape:
- M. O'Brien, M. Schildhauer, S. Chong, R. Miller. 2018. Measurement Ontologies: A Field of Dreams for Essential Biodiversity Variables. https://doi.org/10.1002/essoar.10500833.1

**Comment by SarahRDBingo** [comment]
@albenson-usgs I am working with benthic data right now that measures corals/sponges in terms of percent area of a survey quadrat. I've searched for 'Percent Area', 'Area Percent', and 'Percent Cover'. The P06 collection of terms on NERC closest match was 'Percent', which is a bit ambiguous. Other collections like the one @mobb supplied from BioPortal Boontology contain a more precise vocabulary for ['Area Percent'](http://purl.dataone.org/odo/ECSO_00001195). 

Should we restrict ourselves to a single collection of terms, or is it better to find terms more suited to the measurement type? Should we consider requesting Area Percent as a measurement unit to be added to the NERC P06?

**Comment by albenson-usgs** [comment]
@SarahRDBingo I don't think we need to limit ourselves to one vocabulary. If you find a match for your term in another collection then you should use. As long as the collection is stable and will be around for the foreseeable future, then that works great in my view! We can also request to add the term to the NERC vocabulary but since you found it elsewhere- makes more sense to use that.

**Comment by 7yl4r** [comment]
Looking at some existing OBIS data, the CREMP data down here uses a measurement or fact `Organism Quantity (x100=%cover)`. I don't know what vocab (if any) that is coming from.

**Comment by albenson-usgs** [comment]
Best place to add missing terms is here: https://github.com/nvs-vocabs
