### ISSUE TITLE
enable github pages?

### ISSUE THREAD

**Issue by Br-Johnson** [ioos/bio_data_guide#36]
@mwengren Hi Micah! Would you mind enabling github pages for this repository? I'd like to host our Standardizing Marine Bio Date Guide there. Thanks!

**Comment by mwengren** [comment]
Hi @Br-Johnson, I looked at the Settings menu, and it looks like it already is: https://ioos.github.io/bio_data_guide/.  To make changes, just edit or submit PRs to the 'gh-pages' branch and that should do it.

**Comment by mwengren** [comment]
Quick update, sorry.  Checking again it's currently set to use the master branch to serve the GitHub Pages site.  To change that, I think you would first need to push a 'gh-pages' branch (or whatever you want to call it), and then perhaps @albenson-usgs or if not I can update the settings accordingly.

**Comment by albenson-usgs** [comment]
Github novice here so I'm not sure I understand what needs to happen but happy to do it if someone can walk me through it :-)

**Comment by 7yl4r** [comment]
Also worth considering: Github has an option for using the `/docs` directory on the master branch.
I think modifying branches is less beginner-friendly, but on the other hand: website editing is not really a beginner activity.

@Br-Johnson : what tech are you planning to use to build the site?
Would you prefer to use gh-pages or the /docs directory?

**Comment by Br-Johnson** [comment]
I’m using a Hugo backend to build static HTML files from markdown or R markdown files, using the bookdown pkg in R. 

I think the docs folder would be great. I agree with Tylar editing branches isn’t beginner friendly. 

Currently, there’s a docs folder in the ‘Standardizing Marine Bio....’ folder. Ideally, point github pages to the docs sub-directory on master branch. If I have to move docs to root I can, just not sure the customization through github settings to specify sub folders for gh pages. 

Thanks

**Comment by mwengren** [comment]
Here's what I see from the settings menu:

![ioos_bio_data_guide_ghpages](https://user-images.githubusercontent.com/1469921/82208234-2daf2680-98d9-11ea-86ef-c5f79d6bc730.png)


If I'm the only one who has access to modify GitHub Pages settings, then I'll have to make whatever changes are decided on, but it seems that the /docs subfolder on the master branch must first exist before it can be used.  So I'd say go ahead and upload whatever you want to post to /docs, and ping me again to make the change.

**Comment by Br-Johnson** [comment]
@mwengren Thanks, the docs folder is on the master branch now. So you should have the option now to select docs.

**Comment by mwengren** [comment]
Ok, change made via Settings.  Not sure if the public page was rebuilt or not as a result, but I think all the pieces are in place:

![Screenshot](https://user-images.githubusercontent.com/1469921/82554273-a01b4300-9b33-11ea-80b3-cdb9c3227fd4.png)

**Comment by Br-Johnson** [comment]
@mwengren could you update the link github shows for the repo by adding /intro.html to the end? It should read https://ioos.github.io/bio_data_guide/intro.html

Thanks! I need to fix the root to redirect to intro...

**Comment by mwengren** [comment]
@Br-Johnson all set.  I think if you change your markdown files so they generate an index.html that should make the full path unnecessary.
