### ISSUE TITLE
Repository name change/restructure?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_data_guide#38]
Hi All,

This is a great resource! Thank you all for spending the time to build this. As I'm reviewing the content in this repository, I have some questions. From what I can tell, this repository is primarily focused on providing examples and resources for translating biological data into DwC. Is that the intention? Or, is the plan to expand this repository to cover all types of biological data (eg. acoustics, video, eDNA, etc.)? Some of the language indicates it's the latter, but the content doesn't reflect that.

My personal opinion would be to keep this as is but change the name and some of the content to explicitly state this repository is a "DwC data guide". Then, as other pieces of the biological landscape build out, we can create more data guides. 

Any thoughts?

**Comment by albenson-usgs** [comment]
I guess I'm not understanding this part "Is the plan to expand this repository to cover all types of biological data (eg. acoustics, video, eDNA). All of those types of data can be modeled using Darwin Core so those are not excluded from this repository. In fact, we already do have examples of video data with the FL CREMP data (although it might not be documented here). What the repo can be used for and getting people to use the repo are two separate things :-)

**Comment by MathewBiddle** [comment]
> What the repo can be used for and getting people to use the repo are two separate things

Agreed!

@albenson-usgs could you share the FL CREMP example? 

I guess I was thinking along the lines of how do we properly manage acoustic (or video) data? mp3 files? What kind of metadata is recommended to include? Are there standard products that should be generated from them? etc...

I think the FL CREMP example will help shed light on how DwC can manage video data. Is there some DwC documentation out there that shows how to model these other, non-tabular, data?

**Comment by sbeaulieu** [comment]
@MathewBiddle With regard to 'how do we properly manage' 'other, non-tabular, data': over the past 1.5 yrs a group of LTER Information managers has been meeting as a 'Non-Tabular Working Group'. We are about to present our best practices to the full network of LTER IMs in December. The BP's have general concepts but include details tailored to the EDI repo and EML metadata standard.

**Comment by MathewBiddle** [comment]
@sbeaulieu I'd love to hear more about that!

**Comment by jdpye** [comment]
this might be the dataset in question: https://obis.org/dataset/36bca81c-6d77-4fd4-a981-65d494197fc5 ?

**Comment by mobb** [comment]
Commenting on an earlier bit of this thread:https://github.com/ioos/bio_data_guide/issues/38#issuecomment-712904690

The LTER/EDI "non-tablular" working group  that @sbeaulieu  mentioned is focused on describing these non-traditional data objects _in the manner best suited to that data, including format_. 

I agree with @MathewBiddle  - that so far, this repository seems most focused on describing data in the DwC-A format, in which multiple types data can be _constrained to a format suited to a particular type of query_. 

Both are valuable contributions, but have different objectives, assumptions and starting conditions. Both also use EML, but in different ways.

**Comment by albenson-usgs** [comment]
This repo is open to anyone who wants to add content :-) I do think it's worth noting that this repo as stated in the README is for "IOOS's best practices for biological data".

**Comment by mobb** [comment]
thats great! you should rope in the stuff the MBONs did back in 2015. Its in an Axiom data-space, but we never found a good home for it at IOOS.

**Comment by MathewBiddle** [comment]
@mobb, thank you for clearly articulating my poorly described discussion topic, this https://github.com/ioos/bio_data_guide/issues/38#issuecomment-713118970 hits the nail on the head. 

I'm interested in the 2015 MBON resources and what they might contain.
