### ISSUE TITLE
Write up a Use Case for events with subsamples

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_data_guide#41]
Example is tows where you do an aggregated weight but also a subsample with individual weights/lengths. Some relevant information here: https://github.com/iobis/env-data/issues/10

**Comment by 7yl4r** [comment]
For the example where you are recording the weight of the tow, shouldn't that information be a measurement or fact on the event including each occurrence? No sub-occurrences needed.

**Comment by albenson-usgs** [comment]
This one would be good for the bio-data-guide because it comes up fairly often.

**Comment by MathewBiddle** [comment]
@timvdstap I think your recent example addresses this ticket: https://ioos.github.io/bio_data_guide/applications.html#trawl-data

If so, please close.

**Comment by MathewBiddle** [comment]
This is done.
