### ISSUE TITLE
Expand ERDDAP documentation to provide MBON best practices in configuration

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_data_guide#44]
We should be documenting some of the nuances when serving DwC data via ERDDAP. 

For example, if the date is only captured to the year, the ERDDAP configuration for that time variable should only treat it as a string, not a time in seconds since 1970. 

I know there are other items, similar to above, which should be documented. I'll look at some of my notes and compile them here.

Here is the current section that should be updated: https://ioos.github.io/bio_data_guide/intro.html#erddap

**Comment by MathewBiddle** [comment]
HakaiInstitute has a start to this https://github.com/HakaiInstitute/erddap-basic. But, I'd really like to get to the nuts-and-bolts of configuring a DwC dataset in ERDDAP. 

Some questions:

* What `dataTypes` do we set for which 'columns' in DwC? Are there any specifics we should be identifying? 
* How should the `datasetID` be configured? 
* Identification of primary latitude, longitude, depth (in meters), and time variables.
* What about populating the metadata for each column? How do we recommend doing that?
* What about the global metadata? Can we map to EML?

**Comment by albenson-usgs** [comment]
GCOOS has done this work already so we should get input from Marion Stoessel but I don't see her here in the Github. @SarahRDBingo might be interested in this as she is working to stand up an ERDDAP for PacIOOS Biological Data.

**Comment by MathewBiddle** [comment]
@fgayanilo might be good to ping from GCOOS as well.

**Comment by MathewBiddle** [comment]
This isn't appropriate anymore.
