### ISSUE TITLE
Add instructions for building the Standardizing-Marine-Biological-Data book

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_data_guide#46]
@Br-Johnson  In [CONTRIBUTING.md](https://github.com/ioos/bio_data_guide/blob/master/Standardizing%20Marine%20Biological%20Data/CONTRIBUTING.md) there is this statement:
> I build all the chapters into the book using bookdown and the technologies wraped by that.

Could we include the instructions for building [the book](https://ioos.github.io/bio_data_guide/intro.html)? Maybe stick those in the [wiki page](https://github.com/ioos/bio_data_guide/wiki)?

As an after thought, I'm wondering if there is an easier technology to use, like [JupyterBook](https://jupyterbook.org/intro.html), which could facilitate more contributions? 

Or, maybe we setup GitHub actions to build the chapters?

**Comment by 7yl4r** [comment]
+1 for github actions

**Comment by MathewBiddle** [comment]
I'm willing to try to build github actions, if someone points me to how to build the book using bookdown.

**Comment by Br-Johnson** [comment]
Just seeing this now after some vacation time. Sounds good I will add some instructions for building the book and  if it's too complicated with installing tex  and markdown  etc I'm  happy to  transition to something simpler!

**Comment by Br-Johnson** [comment]
I added instructions for building the book in R Studio in the CONTRIBUTING.md file. Hopefully, these instructions will work for those wanting to contribute to the book and then build the output formats. 

I'm not familiar with using GH actions to build R Markdown books. I'm not sure that's possible? If building the book using R Studio proves too cumbersome, I'm happy to let someone else take the lead on exploring building this book with simpler technology.

**Comment by MathewBiddle** [comment]
Thanks @Br-Johnson! At least we have some instructions now. We can evaluate other resources another time. 

FWIW I tried to make changes to one of the pages and realized I changed the wrong .Rmd file. Maybe if I used R Studio to make the change it would have been easier.
