### ISSUE TITLE
Add a section on sharing data with OBIS

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_data_guide#50]
Once you have a DwC-A compliant package, how do you submit to OBIS/GBIF?

Right now, one process is send an email with attachments to the appropriate person.

Can we identify a more fluid, open, less intensive process?

**Comment by Br-Johnson** [comment]
What are the guidelines in the US for having an Integrated Publishing Toolkit (IPT) account? Being able to log in and create the record and test it etc. yourself is how we do it at OBIS Canada. That being said, we kind of skip that initial QA step of having someone look things over before publishing, and opt for a post hoc review (which is probably more likely to get skipped, unfortunately).

**Comment by albenson-usgs** [comment]
I do have the ability to add users to the OBIS-USA IPT but it will still be a manual process to add the data.

**Comment by MathewBiddle** [comment]
See https://manual.obis.org/contribute.html. No need to replicate that information here. Closing.
