### ISSUE TITLE
Preferred technology for building and contributing to the guide

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_data_guide#51]
I've been trying to build the book using Rstudio and it hasn't been the easiest experience. 

My thought was that if I could get [this GHA (on my fork)](https://github.com/MathewBiddle/bio_data_guide/blob/master/.github/workflows/deploy_bookdown.yml) to work , we wouldn't have to build the site locally then push. It would all be automated, making it easier to contribute material.

Well, I keep [running into issues](https://github.com/MathewBiddle/bio_data_guide/runs/3498408620?check_suite_focus=true) when compiling 03-application.Rmd and I have no clue how to debug bookdown.

So, I'd like to ask the users and contributors to the guide: What is a good solution to create a guide and facilitate contributions? 

Is everyone comfortable with bookdown? Should we look at github pages? jupyterbook? gitbook? something else?

Open for discussion.

**Comment by MathewBiddle** [comment]
Also, this could be an artifact of my limited knowledge, but I can't figure out why there are soo many docs in this repo. 

I see these places where docs exist:
- https://github.com/ioos/bio_data_guide/tree/master/docs
- https://github.com/ioos/bio_data_guide/tree/master/Standardizing%20Marine%20Biological%20Data
- https://github.com/ioos/bio_data_guide/tree/master/Standardizing%20Marine%20Biological%20Data/docs

Where is the authoritative place to edit the files?

**Comment by 7yl4r** [comment]
RE the issues: I wonder if the "unused argument" error is due to a versioning difference. I don't have much preference on what tech does the building but I agree that github actions is the way to go.

RE the multiple docs folders: afraid I can't speak to which is best but when this gets figured out we should add some basic explaination of the directory structure to the README.

**Comment by 7yl4r** [comment]
Some notes on what I we think is going on with the multiple directories:

* edit files in `bio_data_guide/Standardizing Marine Biological Data/`
* bookdown will build the Rmd files into .md & .html into `bio_data_guide/Standardizing Marine Biological Data/docs/`
* all that gets copied into `bio_data_guide/docs/`
* github pages serves out of docs to the web

@Br-Johnson : can you confirm this is how things work?

**Comment by bbest** [comment]
Hi @MathewBiddle,

Here's the comparison of before and after getting this build to  work:

https://github.com/bbest/bio_data_guide/compare/e1bce18..eb1342


## fixed errors rendering `03-application.Rmd`

Let's review commit https://github.com/bbest/bio_data_guide/commit/a03e847aad69d236b9e8fd617cd5d49d94d4d3fc to fix your [failed build](https://github.com/MathewBiddle/bio_data_guide/runs/3534516054?check_suite_focus=true#step:7:78) for the Github action [deploy_bookdown.yml](
https://github.com/MathewBiddle/bio_data_guide/blob/f5261871cdc48e42d9dadd503f6845a71295cf6f/.github/workflows/deploy_bookdown.yml):

```
Quitting from lines 106-206 (03-application.Rmd) 
Error in rename(., eventID = seine_id) : 
  unused argument (eventID = seine_id)
```

###  Error in `rename()`

When I tried running the Rscript part of [deploy_bookdown.yml](
https://github.com/MathewBiddle/bio_data_guide/blob/f5261871cdc48e42d9dadd503f6845a71295cf6f/.github/workflows/deploy_bookdown.yml) on my local machine after forking and cloning:

```r
setwd("Standardizing Marine Biological Data")
bookdown::render_book("index.Rmd")
```

And then ran all chunks in `03-application.Rmd` up to the offending chunk in `lines 106-206`. The `rename()` function I'm used to using in `dplyr` looks correct to me, but then I enter `rename` into the Console to see which package its coming from:

```
rename
...
<environment: namespace:plyr>
```

So I explicitly defined rename at the top where libraries get loaded:

```r
rename = dplyr::rename
```

### `wm_records_names' not found

Once I got past that previous error, I got:

```
`wm_records_names' not found
```

To see which package this might come from, I ran in the Console:

```r
??wm_records_names
```

This shows me help for: `wm_records_names {worrms}` (upper left  of help  doc), so from the `worrms` (not `worms`) R package, so added `library(worrms)`.

## fixed R package loading issues

Gotta switch gears, but here's a comparison of all the changes:

https://github.com/bbest/bio_data_guide/compare/e1bce18..27a5bb3

Hopefully this last fix gets the `checkout-and-deploy` step to work in this [run](https://github.com/bbest/bio_data_guide/actions/runs/1242079034)

**Comment by MathewBiddle** [comment]
This is awesome @bbest!! Thank you for taking a look at it and working through some of the troubles. The `worrms` -> `worms` was something I did, thinking it was a misspelling, good catch. I'll merge in your PR to my fork and see where that gets us. 

Again, thanks for taking a look!
