### ISSUE TITLE
Do we want to reorganize the content in this book?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_data_guide#89]
Do folks who are new to working with DwC find the organization of this book at the right level? Should we try to reorganize the content into a workflow or is the way it's organized sufficient?
![image](https://user-images.githubusercontent.com/8480023/149028061-a976e716-dbf1-48d8-81dd-5d43e3473c66.png)

https://ioos.github.io/bio_data_guide/

@emiliom you may have some thoughts?

**Comment by albenson-usgs** [comment]
Wondering if we should have this as a topic for the February SMBD meeting. Seems like it could use some discussion.

**Comment by emiliom** [comment]
I like @albenson-usgs 's suggestion. And BTW, I do have thoughts on how useful this guide is / isn't in its current form.

**Comment by MathewBiddle** [comment]
Fantastic, lets push it to February.

I think either linking to or copying some of the content from https://ioos.github.io/bio_mobilization_workshop/01-introduction/index.html would be nice.

**Comment by MathewBiddle** [comment]
Thinking about the applications section a little more. I proposed that we should have examples of different categories of data/observation types. For example:

- [ ] Net collection (sample/sub-sample) @timvdstap
- [ ] eDNA extension, which we have an example of at iobis. Just like to it here?
- [ ] IFCB images @sbeaulieu
- [ ] passive acoustic @albenson-usgs mentioned some conversations have started.
- [ ] Others?

This wouldn't be an exhaustive collection, but examples of the more common (or emerging) types.

**Comment by MathewBiddle** [comment]
I'm going to close this issue and open a new one for "Needed examples to include"
