### ISSUE TITLE
Application section not updating when markdown updates

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_data_guide#96]
See: https://github.com/ioos/bio_data_guide/blob/main/datasets/TPWD_HARC_BagSeine/TPWD_HARC_BagSeine_OBISENV.md
vs
https://ioos.github.io/bio_data_guide/applications.html#aligning-data-to-darwin-core---sampling-event-with-measurement-or-fact

**Comment by MathewBiddle** [comment]
@albenson-usgs I was pointing to https://github.com/ioos/bio_data_guide/blob/main/datasets/example_script_with_fake_data/IOOS_DMAC_DataToDwC_Notebook_event.md

Should I change it to the TPWD markdown?

**Comment by albenson-usgs** [comment]
Oh! Yes let's change it to the newer one. It's cleaner code and updated text (e.g. Measurement or Fact -> Extended Measurement or Fact)
